//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teste.Models
{
    using System;
    using System.Linq;

    public partial class Usuario
    {
        public int Id { get; set; }
        public string NomeUsuario { get; set; }
        public string Login { get; set; }
        public string Salt { get; set; }
        public string Hash { get; set; }

        /// <summary>
        /// Busca o usuário 
        /// </summary>
        /// <param name="login"></param>
        /// <returns></returns>
        public static Usuario BuscarUsuario(string login)
        {
            try
            {
                //Cria o contexto do entity Framework para fazer a pesquisa na base de dados
                using (var db = new ViaVarejoDBEntities())
                {
                    //Lambda Expression para buscar o usuário no Banco.
                    //Caso não encontre, retorna nulo.
                    return db.Usuarios.Where(p => p.Login == login).FirstOrDefault();
                }
            }
            catch (Exception ex)
            {
                throw new Exception($"Problemas ao buscar usuário: {login}. Erro: { ex.Message }");
            }
        }
    }

}
